//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFS_Rekrutacja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sentences
    {
        public int ID { get; set; }
        public string Text { get; set; }
        public string TranslatedText { get; set; }
        public int TranslationID { get; set; }
    
        public virtual Translations Translations { get; set; }
    }
}
