//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AFS_Rekrutacja.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Translations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Translations()
        {
            this.Sentences = new HashSet<Sentences>();
        }
    
        public int ID { get; set; }
        public string TranslationName { get; set; }
        public string TranslationUrl { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sentences> Sentences { get; set; }
    }
}
